version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/django-postgres
    ports:
      - 8000:8000
    image: app:django-postgres
    container_name: django_postgres_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    container_name: the_django_postgres_container